# Generated by Django 4.2.7 on 2023-11-30 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_rent',
            old_name='costo_diario',
            new_name='daily_cost',
        ),
        migrations.RenameField(
            model_name='client_rent',
            old_name='dias',
            new_name='days',
        ),
        migrations.RenameField(
            model_name='client_rent',
            old_name='id_cliente',
            new_name='id_client',
        ),
        migrations.RenameField(
            model_name='client_rent',
            old_name='id_empresa',
            new_name='id_company',
        ),
    ]
