# Generated by Django 4.2.7 on 2023-11-30 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_costo_diario_client_rent_daily_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_rent',
            old_name='id_client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='client_rent',
            old_name='id_company',
            new_name='company',
        ),
    ]
