# Generated by Django 4.2.7 on 2023-11-30 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_id_client_client_rent_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_rent',
            old_name='client',
            new_name='id_client',
        ),
        migrations.RenameField(
            model_name='client_rent',
            old_name='company',
            new_name='id_company',
        ),
    ]
